# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
rss: /atom.xml


# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico into `hexo-site/themes/hipaper/source/` directory.
favicon: css/images/favicon.ico


# Put your avatar.jpg into `hexo-site/themes/hipaper/source/` directory.
avatar: 
  enable: false
  width: 124
  height: 124
  bottom: 10
  url: css/images/mylogo.jpg


# AboutPage background, support multiple images.
about_big_image: [css/images/pose01.jpg, css/images/pose02.jpg]


# Homepage thumbnail
random_thumb: false


# Content
fancybox: true


# Sidebar
sidebar: right
widgets:
- search
- social
- recent_posts
- category
- tag
- tagcloud
- archive

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Github: https://github.com/iTimeTraveler
  Weibo: 
  Twitter: 
  Facebook: 
  Google-plus: 
  Instagram: 


# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# comment ShortName, you can choose only ONE to display.
duoshuo_shortname: iTimeTraveler
disqus_shortname:


# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:
baidu_site_verification:
qihu_site_verification:

# Miscellaneous
google_analytics:
gauges_analytics:
baidu_analytics:
tencent_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# CNZZ count
cnzz_siteid: 1260716016
